### ISSUE TITLE
expected close marker for OBJECT when generate deoloyment mainifest

### ISSUE THREAD

**Issue by czgtest** [Microsoft/azure-iot-edge-jenkins-plugin#9]
http://10.172.14.160:8080/job/TestVS2017/7/console 
![image](https://user-images.githubusercontent.com/35018765/59756849-1b89ca00-92bd-11e9-9884-0a13e74ed3af.png)

![image](https://user-images.githubusercontent.com/35018765/59756874-2a707c80-92bd-11e9-8574-c21f5a218ad2.png)

**Comment by formulahendry** [comment]
Seems a random issue, please help run again to see if issue still exists.

**Comment by czgtest** [comment]
this issue is not repro today,  generate deoloyment mainifest work well
